
/**************************************************************
 *	
 *	attackZap, 8 bit, 11025Hz,
 *	1 channel, 12381 bytes/channel
 *	Total Size: 1 * 12381 + 4 (header) = 12425 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	G:\CS2261\Final Project\M5\attackZap.wav
 *	Time-stamp: Mon Apr 24 20:41:05 2017
 *	
 **************************************************************/

#ifndef __ATTACKZAPH__
#define __ATTACKZAPH__

#define ATTACKZAPFREQ 11025
#define ATTACKZAPLEN 12381

extern const unsigned char attackZap[12381];

#endif /* __ATTACKZAPH__ */
