
/**************************************************************
 *	
 *	attackZap, 8 bit, 11025Hz,
 *	1 channel, 5632 bytes/channel
 *	Total Size: 1 * 5632 + 4 (header) = 5676 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	G:\CS2261\Final Project\M3\attackZap.wav
 *	Time-stamp: Tue Apr 04 22:31:44 2017
 *	
 **************************************************************/

#ifndef __ATTACKZAPH__
#define __ATTACKZAPH__

#define ATTACKZAPFREQ 11025
#define ATTACKZAPLEN 5632

extern const unsigned char attackZap[5632];

#endif /* __ATTACKZAPH__ */
