
/**************************************************************
 *	
 *	gameMusic, 8 bit, 11025Hz,
 *	1 channel, 2428992 bytes/channel
 *	Total Size: 1 * 2428992 + 4 (header) = 2429036 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	G:\CS2261\Final Project\M3\gameMusic.wav
 *	Time-stamp: Tue Apr 04 22:31:53 2017
 *	
 **************************************************************/

#ifndef __GAMEMUSICH__
#define __GAMEMUSICH__

#define GAMEMUSICFREQ 11025
#define GAMEMUSICLEN 2428992

extern const unsigned char gameMusic[2428992];

#endif /* __GAMEMUSICH__ */
