
/**************************************************************
 *	
 *	winSong, 8 bit, 11025Hz,
 *	1 channel, 42924 bytes/channel
 *	Total Size: 1 * 42924 + 4 (header) = 42968 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	G:\CS2261\Final Project\M5\winSong.wav
 *	Time-stamp: Mon Apr 24 20:42:26 2017
 *	
 **************************************************************/

#ifndef __WINSONGH__
#define __WINSONGH__

#define WINSONGFREQ 11025
#define WINSONGLEN 42924

extern const unsigned char winSong[42924];

#endif /* __WINSONGH__ */
